fix = true
indent-width = 2
line-length = 88
respect-gitignore = true
target-version = "py311"

builtins = ["_"]
# src = []
# include = []

[format]
docstring-code-format = true
docstring-code-line-lenght = 88
indent-style = "space"
line-ending = "lf"
quote-style = "double"
skip-magic-trailing-comma = false

